# Function options
handler: service.handler
description: Scale batch compute environments down when mincpus != desiredcpus
runtime: python3.8
timeout: 60
memory_size: 128
concurrency: 1
bucket_name: 'pipeline.poc'
s3_key_prefix: 'lambda/testfunc/'

# Build options
dist_directory: dist
# build:
#   source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
